export const responses = [
    {
        response: {
            headers: [
                {
                    name: 'dx',
                    column: 'Data',
                    valueType: 'TEXT',
                    type: 'java.lang.String',
                    hidden: false,
                    meta: true,
                },
                {
                    name: 'ou',
                    column: 'Organisation unit',
                    valueType: 'TEXT',
                    type: 'java.lang.String',
                    hidden: false,
                    meta: true,
                },
                {
                    name: 'value',
                    column: 'Value',
                    valueType: 'NUMBER',
                    type: 'java.lang.Double',
                    hidden: false,
                    meta: false,
                },
            ],
            metaData: {
                items: {
                    202404: {
                        uid: '202404',
                        code: '202404',
                        name: 'April 2024',
                        dimensionItemType: 'PERIOD',
                        valueType: 'TEXT',
                        totalAggregationType: 'SUM',
                        startDate: '2024-04-01T00:00:00.000',
                        endDate: '2024-04-30T00:00:00.000',
                    },
                    202405: {
                        uid: '202405',
                        code: '202405',
                        name: 'May 2024',
                        dimensionItemType: 'PERIOD',
                        valueType: 'TEXT',
                        totalAggregationType: 'SUM',
                        startDate: '2024-05-01T00:00:00.000',
                        endDate: '2024-05-31T00:00:00.000',
                    },
                    202406: {
                        uid: '202406',
                        code: '202406',
                        name: 'June 2024',
                        dimensionItemType: 'PERIOD',
                        valueType: 'TEXT',
                        totalAggregationType: 'SUM',
                        startDate: '2024-06-01T00:00:00.000',
                        endDate: '2024-06-30T00:00:00.000',
                    },
                    202407: {
                        uid: '202407',
                        code: '202407',
                        name: 'July 2024',
                        dimensionItemType: 'PERIOD',
                        valueType: 'TEXT',
                        totalAggregationType: 'SUM',
                        startDate: '2024-07-01T00:00:00.000',
                        endDate: '2024-07-31T00:00:00.000',
                    },
                    202408: {
                        uid: '202408',
                        code: '202408',
                        name: 'August 2024',
                        dimensionItemType: 'PERIOD',
                        valueType: 'TEXT',
                        totalAggregationType: 'SUM',
                        startDate: '2024-08-01T00:00:00.000',
                        endDate: '2024-08-31T00:00:00.000',
                    },
                    202409: {
                        uid: '202409',
                        code: '202409',
                        name: 'September 2024',
                        dimensionItemType: 'PERIOD',
                        valueType: 'TEXT',
                        totalAggregationType: 'SUM',
                        startDate: '2024-09-01T00:00:00.000',
                        endDate: '2024-09-30T00:00:00.000',
                    },
                    202410: {
                        uid: '202410',
                        code: '202410',
                        name: 'October 2024',
                        dimensionItemType: 'PERIOD',
                        valueType: 'TEXT',
                        totalAggregationType: 'SUM',
                        startDate: '2024-10-01T00:00:00.000',
                        endDate: '2024-10-31T00:00:00.000',
                    },
                    202411: {
                        uid: '202411',
                        code: '202411',
                        name: 'November 2024',
                        dimensionItemType: 'PERIOD',
                        valueType: 'TEXT',
                        totalAggregationType: 'SUM',
                        startDate: '2024-11-01T00:00:00.000',
                        endDate: '2024-11-30T00:00:00.000',
                    },
                    202412: {
                        uid: '202412',
                        code: '202412',
                        name: 'December 2024',
                        dimensionItemType: 'PERIOD',
                        valueType: 'TEXT',
                        totalAggregationType: 'SUM',
                        startDate: '2024-12-01T00:00:00.000',
                        endDate: '2024-12-31T00:00:00.000',
                    },
                    202501: {
                        uid: '202501',
                        code: '202501',
                        name: 'January 2025',
                        dimensionItemType: 'PERIOD',
                        valueType: 'TEXT',
                        totalAggregationType: 'SUM',
                        startDate: '2025-01-01T00:00:00.000',
                        endDate: '2025-01-31T00:00:00.000',
                    },
                    202502: {
                        uid: '202502',
                        code: '202502',
                        name: 'February 2025',
                        dimensionItemType: 'PERIOD',
                        valueType: 'TEXT',
                        totalAggregationType: 'SUM',
                        startDate: '2025-02-01T00:00:00.000',
                        endDate: '2025-02-28T00:00:00.000',
                    },
                    202503: {
                        uid: '202503',
                        code: '202503',
                        name: 'March 2025',
                        dimensionItemType: 'PERIOD',
                        valueType: 'TEXT',
                        totalAggregationType: 'SUM',
                        startDate: '2025-03-01T00:00:00.000',
                        endDate: '2025-03-31T00:00:00.000',
                    },
                    jUb8gELQApl: {
                        uid: 'jUb8gELQApl',
                        code: 'OU_204856',
                        name: 'Kailahun',
                        dimensionItemType: 'ORGANISATION_UNIT',
                        valueType: 'TEXT',
                        totalAggregationType: 'SUM',
                    },
                    eIQbndfxQMb: {
                        uid: 'eIQbndfxQMb',
                        code: 'OU_268149',
                        name: 'Tonkolili',
                        dimensionItemType: 'ORGANISATION_UNIT',
                        valueType: 'TEXT',
                        totalAggregationType: 'SUM',
                    },
                    Vth0fbpFcsO: {
                        uid: 'Vth0fbpFcsO',
                        code: 'OU_233310',
                        name: 'Kono',
                        dimensionItemType: 'ORGANISATION_UNIT',
                        valueType: 'TEXT',
                        totalAggregationType: 'SUM',
                    },
                    O6uvpzGd5pu: {
                        uid: 'O6uvpzGd5pu',
                        code: 'OU_264',
                        name: 'Bo',
                        dimensionItemType: 'ORGANISATION_UNIT',
                        valueType: 'TEXT',
                        totalAggregationType: 'SUM',
                    },
                    bL4ooGhyHRQ: {
                        uid: 'bL4ooGhyHRQ',
                        code: 'OU_260377',
                        name: 'Pujehun',
                        dimensionItemType: 'ORGANISATION_UNIT',
                        valueType: 'TEXT',
                        totalAggregationType: 'SUM',
                    },
                    kJq2mPyFEHo: {
                        uid: 'kJq2mPyFEHo',
                        code: 'OU_222616',
                        name: 'Kenema',
                        dimensionItemType: 'ORGANISATION_UNIT',
                        valueType: 'TEXT',
                        totalAggregationType: 'SUM',
                    },
                    wjP19dkFeIk: {
                        uid: 'wjP19dkFeIk',
                        name: 'District',
                    },
                    LAST_12_MONTHS: {
                        name: 'Last 12 months',
                    },
                    ImspTQPwCqd: {
                        uid: 'ImspTQPwCqd',
                        code: 'OU_525',
                        name: 'Sierra Leone',
                    },
                    at6UHUQatSo: {
                        uid: 'at6UHUQatSo',
                        code: 'OU_278310',
                        name: 'Western Area',
                        dimensionItemType: 'ORGANISATION_UNIT',
                        valueType: 'TEXT',
                        totalAggregationType: 'SUM',
                    },
                    dx: {
                        uid: 'dx',
                        name: 'Data',
                        dimensionType: 'DATA_X',
                    },
                    Uvn6LCg7dVU: {
                        uid: 'Uvn6LCg7dVU',
                        code: 'IN_52486',
                        name: 'ANC 1 Coverage',
                        description:
                            'Total 1st ANC visits (Fixed and outreach) by expected number of pregnant women.',
                        legendSet: 'fqs276KXCXi',
                        dimensionItemType: 'INDICATOR',
                        valueType: 'NUMBER',
                        totalAggregationType: 'AVERAGE',
                        indicatorType: {
                            name: 'Per cent',
                            displayName: 'Per cent',
                            factor: 100,
                            number: false,
                        },
                    },
                    TEQlaapDQoK: {
                        uid: 'TEQlaapDQoK',
                        code: 'OU_254945',
                        name: 'Port Loko',
                        dimensionItemType: 'ORGANISATION_UNIT',
                        valueType: 'TEXT',
                        totalAggregationType: 'SUM',
                    },
                    PMa2VCrupOd: {
                        uid: 'PMa2VCrupOd',
                        code: 'OU_211212',
                        name: 'Kambia',
                        dimensionItemType: 'ORGANISATION_UNIT',
                        valueType: 'TEXT',
                        totalAggregationType: 'SUM',
                    },
                    ou: {
                        uid: 'ou',
                        name: 'Organisation unit',
                        dimensionType: 'ORGANISATION_UNIT',
                    },
                    fdc6uOvgoji: {
                        uid: 'fdc6uOvgoji',
                        code: 'OU_193190',
                        name: 'Bombali',
                        dimensionItemType: 'ORGANISATION_UNIT',
                        valueType: 'TEXT',
                        totalAggregationType: 'SUM',
                    },
                    pe: {
                        uid: 'pe',
                        name: 'Period',
                        dimensionType: 'PERIOD',
                    },
                    ReUHfIn0pTQ: {
                        uid: 'ReUHfIn0pTQ',
                        code: 'IN_52462',
                        name: 'ANC 1-3 Dropout Rate',
                        description:
                            'Indicates the percentage of clients dropping out between the 1st and the 3rd ANC visit. Calculated as the difference between ANC1 and ANC3 by the ANC 1 visits.',
                        dimensionItemType: 'INDICATOR',
                        valueType: 'NUMBER',
                        totalAggregationType: 'AVERAGE',
                        indicatorType: {
                            name: 'Per cent',
                            displayName: 'Per cent',
                            factor: 100,
                            number: false,
                        },
                    },
                    lc3eMKXaEfw: {
                        uid: 'lc3eMKXaEfw',
                        code: 'OU_197385',
                        name: 'Bonthe',
                        dimensionItemType: 'ORGANISATION_UNIT',
                        valueType: 'TEXT',
                        totalAggregationType: 'SUM',
                    },
                    qhqAxPSTUXp: {
                        uid: 'qhqAxPSTUXp',
                        code: 'OU_226213',
                        name: 'Koinadugu',
                        dimensionItemType: 'ORGANISATION_UNIT',
                        valueType: 'TEXT',
                        totalAggregationType: 'SUM',
                    },
                    jmIPBj66vD6: {
                        uid: 'jmIPBj66vD6',
                        code: 'OU_246990',
                        name: 'Moyamba',
                        dimensionItemType: 'ORGANISATION_UNIT',
                        valueType: 'TEXT',
                        totalAggregationType: 'SUM',
                    },
                },
                dimensions: {
                    dx: ['ReUHfIn0pTQ', 'Uvn6LCg7dVU'],
                    pe: [
                        '202404',
                        '202405',
                        '202406',
                        '202407',
                        '202408',
                        '202409',
                        '202410',
                        '202411',
                        '202412',
                        '202501',
                        '202502',
                        '202503',
                    ],
                    ou: [
                        'O6uvpzGd5pu',
                        'fdc6uOvgoji',
                        'lc3eMKXaEfw',
                        'jUb8gELQApl',
                        'PMa2VCrupOd',
                        'kJq2mPyFEHo',
                        'qhqAxPSTUXp',
                        'Vth0fbpFcsO',
                        'jmIPBj66vD6',
                        'TEQlaapDQoK',
                        'bL4ooGhyHRQ',
                        'eIQbndfxQMb',
                        'at6UHUQatSo',
                    ],
                    co: [],
                },
            },
            rowContext: {},
            rows: [
                ['ReUHfIn0pTQ', 'O6uvpzGd5pu', '35.01'],
                ['ReUHfIn0pTQ', 'fdc6uOvgoji', '37.16'],
                ['ReUHfIn0pTQ', 'lc3eMKXaEfw', '34.94'],
                ['ReUHfIn0pTQ', 'jUb8gELQApl', '14.19'],
                ['ReUHfIn0pTQ', 'PMa2VCrupOd', '37.11'],
                ['ReUHfIn0pTQ', 'kJq2mPyFEHo', '6.77'],
                ['ReUHfIn0pTQ', 'qhqAxPSTUXp', '42.49'],
                ['ReUHfIn0pTQ', 'Vth0fbpFcsO', '28.76'],
                ['ReUHfIn0pTQ', 'jmIPBj66vD6', '21.09'],
                ['ReUHfIn0pTQ', 'TEQlaapDQoK', '52.44'],
                ['ReUHfIn0pTQ', 'bL4ooGhyHRQ', '35.72'],
                ['ReUHfIn0pTQ', 'eIQbndfxQMb', '52.69'],
                ['ReUHfIn0pTQ', 'at6UHUQatSo', '40.99'],
                ['Uvn6LCg7dVU', 'O6uvpzGd5pu', '144.87'],
                ['Uvn6LCg7dVU', 'fdc6uOvgoji', '82.11'],
                ['Uvn6LCg7dVU', 'lc3eMKXaEfw', '90.76'],
                ['Uvn6LCg7dVU', 'jUb8gELQApl', '82.14'],
                ['Uvn6LCg7dVU', 'PMa2VCrupOd', '104.25'],
                ['Uvn6LCg7dVU', 'kJq2mPyFEHo', '94.2'],
                ['Uvn6LCg7dVU', 'qhqAxPSTUXp', '67.78'],
                ['Uvn6LCg7dVU', 'Vth0fbpFcsO', '53.39'],
                ['Uvn6LCg7dVU', 'jmIPBj66vD6', '117.52'],
                ['Uvn6LCg7dVU', 'TEQlaapDQoK', '99.78'],
                ['Uvn6LCg7dVU', 'bL4ooGhyHRQ', '86.91'],
                ['Uvn6LCg7dVU', 'eIQbndfxQMb', '125.62'],
                ['Uvn6LCg7dVU', 'at6UHUQatSo', '121.03'],
            ],
            height: 26,
            width: 3,
            headerWidth: 3,
        },
        headers: [
            {
                name: 'dx',
                column: 'Data',
                valueType: 'TEXT',
                type: 'java.lang.String',
                hidden: false,
                meta: true,
                isPrefix: false,
                isCollect: false,
                index: 0,
            },
            {
                name: 'ou',
                column: 'Organisation unit',
                valueType: 'TEXT',
                type: 'java.lang.String',
                hidden: false,
                meta: true,
                isPrefix: false,
                isCollect: false,
                index: 1,
            },
            {
                name: 'value',
                column: 'Value',
                valueType: 'NUMBER',
                type: 'java.lang.Double',
                hidden: false,
                meta: false,
                isPrefix: false,
                isCollect: false,
                index: 2,
            },
        ],
        rows: [
            ['ReUHfIn0pTQ', 'O6uvpzGd5pu', '35.01'],
            ['ReUHfIn0pTQ', 'fdc6uOvgoji', '37.16'],
            ['ReUHfIn0pTQ', 'lc3eMKXaEfw', '34.94'],
            ['ReUHfIn0pTQ', 'jUb8gELQApl', '14.19'],
            ['ReUHfIn0pTQ', 'PMa2VCrupOd', '37.11'],
            ['ReUHfIn0pTQ', 'kJq2mPyFEHo', '6.77'],
            ['ReUHfIn0pTQ', 'qhqAxPSTUXp', '42.49'],
            ['ReUHfIn0pTQ', 'Vth0fbpFcsO', '28.76'],
            ['ReUHfIn0pTQ', 'jmIPBj66vD6', '21.09'],
            ['ReUHfIn0pTQ', 'TEQlaapDQoK', '52.44'],
            ['ReUHfIn0pTQ', 'bL4ooGhyHRQ', '35.72'],
            ['ReUHfIn0pTQ', 'eIQbndfxQMb', '52.69'],
            ['ReUHfIn0pTQ', 'at6UHUQatSo', '40.99'],
            ['Uvn6LCg7dVU', 'O6uvpzGd5pu', '144.87'],
            ['Uvn6LCg7dVU', 'fdc6uOvgoji', '82.11'],
            ['Uvn6LCg7dVU', 'lc3eMKXaEfw', '90.76'],
            ['Uvn6LCg7dVU', 'jUb8gELQApl', '82.14'],
            ['Uvn6LCg7dVU', 'PMa2VCrupOd', '104.25'],
            ['Uvn6LCg7dVU', 'kJq2mPyFEHo', '94.2'],
            ['Uvn6LCg7dVU', 'qhqAxPSTUXp', '67.78'],
            ['Uvn6LCg7dVU', 'Vth0fbpFcsO', '53.39'],
            ['Uvn6LCg7dVU', 'jmIPBj66vD6', '117.52'],
            ['Uvn6LCg7dVU', 'TEQlaapDQoK', '99.78'],
            ['Uvn6LCg7dVU', 'bL4ooGhyHRQ', '86.91'],
            ['Uvn6LCg7dVU', 'eIQbndfxQMb', '125.62'],
            ['Uvn6LCg7dVU', 'at6UHUQatSo', '121.03'],
        ],
        metaData: {
            items: {
                202404: {
                    uid: '202404',
                    code: '202404',
                    name: 'April 2024',
                    dimensionItemType: 'PERIOD',
                    valueType: 'TEXT',
                    totalAggregationType: 'SUM',
                    startDate: '2024-04-01T00:00:00.000',
                    endDate: '2024-04-30T00:00:00.000',
                },
                202405: {
                    uid: '202405',
                    code: '202405',
                    name: 'May 2024',
                    dimensionItemType: 'PERIOD',
                    valueType: 'TEXT',
                    totalAggregationType: 'SUM',
                    startDate: '2024-05-01T00:00:00.000',
                    endDate: '2024-05-31T00:00:00.000',
                },
                202406: {
                    uid: '202406',
                    code: '202406',
                    name: 'June 2024',
                    dimensionItemType: 'PERIOD',
                    valueType: 'TEXT',
                    totalAggregationType: 'SUM',
                    startDate: '2024-06-01T00:00:00.000',
                    endDate: '2024-06-30T00:00:00.000',
                },
                202407: {
                    uid: '202407',
                    code: '202407',
                    name: 'July 2024',
                    dimensionItemType: 'PERIOD',
                    valueType: 'TEXT',
                    totalAggregationType: 'SUM',
                    startDate: '2024-07-01T00:00:00.000',
                    endDate: '2024-07-31T00:00:00.000',
                },
                202408: {
                    uid: '202408',
                    code: '202408',
                    name: 'August 2024',
                    dimensionItemType: 'PERIOD',
                    valueType: 'TEXT',
                    totalAggregationType: 'SUM',
                    startDate: '2024-08-01T00:00:00.000',
                    endDate: '2024-08-31T00:00:00.000',
                },
                202409: {
                    uid: '202409',
                    code: '202409',
                    name: 'September 2024',
                    dimensionItemType: 'PERIOD',
                    valueType: 'TEXT',
                    totalAggregationType: 'SUM',
                    startDate: '2024-09-01T00:00:00.000',
                    endDate: '2024-09-30T00:00:00.000',
                },
                202410: {
                    uid: '202410',
                    code: '202410',
                    name: 'October 2024',
                    dimensionItemType: 'PERIOD',
                    valueType: 'TEXT',
                    totalAggregationType: 'SUM',
                    startDate: '2024-10-01T00:00:00.000',
                    endDate: '2024-10-31T00:00:00.000',
                },
                202411: {
                    uid: '202411',
                    code: '202411',
                    name: 'November 2024',
                    dimensionItemType: 'PERIOD',
                    valueType: 'TEXT',
                    totalAggregationType: 'SUM',
                    startDate: '2024-11-01T00:00:00.000',
                    endDate: '2024-11-30T00:00:00.000',
                },
                202412: {
                    uid: '202412',
                    code: '202412',
                    name: 'December 2024',
                    dimensionItemType: 'PERIOD',
                    valueType: 'TEXT',
                    totalAggregationType: 'SUM',
                    startDate: '2024-12-01T00:00:00.000',
                    endDate: '2024-12-31T00:00:00.000',
                },
                202501: {
                    uid: '202501',
                    code: '202501',
                    name: 'January 2025',
                    dimensionItemType: 'PERIOD',
                    valueType: 'TEXT',
                    totalAggregationType: 'SUM',
                    startDate: '2025-01-01T00:00:00.000',
                    endDate: '2025-01-31T00:00:00.000',
                },
                202502: {
                    uid: '202502',
                    code: '202502',
                    name: 'February 2025',
                    dimensionItemType: 'PERIOD',
                    valueType: 'TEXT',
                    totalAggregationType: 'SUM',
                    startDate: '2025-02-01T00:00:00.000',
                    endDate: '2025-02-28T00:00:00.000',
                },
                202503: {
                    uid: '202503',
                    code: '202503',
                    name: 'March 2025',
                    dimensionItemType: 'PERIOD',
                    valueType: 'TEXT',
                    totalAggregationType: 'SUM',
                    startDate: '2025-03-01T00:00:00.000',
                    endDate: '2025-03-31T00:00:00.000',
                },
                jUb8gELQApl: {
                    uid: 'jUb8gELQApl',
                    code: 'OU_204856',
                    name: 'Kailahun',
                    dimensionItemType: 'ORGANISATION_UNIT',
                    valueType: 'TEXT',
                    totalAggregationType: 'SUM',
                },
                eIQbndfxQMb: {
                    uid: 'eIQbndfxQMb',
                    code: 'OU_268149',
                    name: 'Tonkolili',
                    dimensionItemType: 'ORGANISATION_UNIT',
                    valueType: 'TEXT',
                    totalAggregationType: 'SUM',
                },
                Vth0fbpFcsO: {
                    uid: 'Vth0fbpFcsO',
                    code: 'OU_233310',
                    name: 'Kono',
                    dimensionItemType: 'ORGANISATION_UNIT',
                    valueType: 'TEXT',
                    totalAggregationType: 'SUM',
                },
                O6uvpzGd5pu: {
                    uid: 'O6uvpzGd5pu',
                    code: 'OU_264',
                    name: 'Bo',
                    dimensionItemType: 'ORGANISATION_UNIT',
                    valueType: 'TEXT',
                    totalAggregationType: 'SUM',
                },
                bL4ooGhyHRQ: {
                    uid: 'bL4ooGhyHRQ',
                    code: 'OU_260377',
                    name: 'Pujehun',
                    dimensionItemType: 'ORGANISATION_UNIT',
                    valueType: 'TEXT',
                    totalAggregationType: 'SUM',
                },
                kJq2mPyFEHo: {
                    uid: 'kJq2mPyFEHo',
                    code: 'OU_222616',
                    name: 'Kenema',
                    dimensionItemType: 'ORGANISATION_UNIT',
                    valueType: 'TEXT',
                    totalAggregationType: 'SUM',
                },
                wjP19dkFeIk: {
                    uid: 'wjP19dkFeIk',
                    name: 'District',
                },
                LAST_12_MONTHS: {
                    name: 'Last 12 months',
                },
                ImspTQPwCqd: {
                    uid: 'ImspTQPwCqd',
                    code: 'OU_525',
                    name: 'Sierra Leone',
                },
                at6UHUQatSo: {
                    uid: 'at6UHUQatSo',
                    code: 'OU_278310',
                    name: 'Western Area',
                    dimensionItemType: 'ORGANISATION_UNIT',
                    valueType: 'TEXT',
                    totalAggregationType: 'SUM',
                },
                dx: {
                    uid: 'dx',
                    name: 'Data',
                    dimensionType: 'DATA_X',
                },
                Uvn6LCg7dVU: {
                    uid: 'Uvn6LCg7dVU',
                    code: 'IN_52486',
                    name: 'ANC 1 Coverage',
                    description:
                        'Total 1st ANC visits (Fixed and outreach) by expected number of pregnant women.',
                    legendSet: 'fqs276KXCXi',
                    dimensionItemType: 'INDICATOR',
                    valueType: 'NUMBER',
                    totalAggregationType: 'AVERAGE',
                    indicatorType: {
                        name: 'Per cent',
                        displayName: 'Per cent',
                        factor: 100,
                        number: false,
                    },
                },
                TEQlaapDQoK: {
                    uid: 'TEQlaapDQoK',
                    code: 'OU_254945',
                    name: 'Port Loko',
                    dimensionItemType: 'ORGANISATION_UNIT',
                    valueType: 'TEXT',
                    totalAggregationType: 'SUM',
                },
                PMa2VCrupOd: {
                    uid: 'PMa2VCrupOd',
                    code: 'OU_211212',
                    name: 'Kambia',
                    dimensionItemType: 'ORGANISATION_UNIT',
                    valueType: 'TEXT',
                    totalAggregationType: 'SUM',
                },
                ou: {
                    uid: 'ou',
                    name: 'Organisation unit',
                    dimensionType: 'ORGANISATION_UNIT',
                },
                fdc6uOvgoji: {
                    uid: 'fdc6uOvgoji',
                    code: 'OU_193190',
                    name: 'Bombali',
                    dimensionItemType: 'ORGANISATION_UNIT',
                    valueType: 'TEXT',
                    totalAggregationType: 'SUM',
                },
                pe: {
                    uid: 'pe',
                    name: 'Period',
                    dimensionType: 'PERIOD',
                },
                ReUHfIn0pTQ: {
                    uid: 'ReUHfIn0pTQ',
                    code: 'IN_52462',
                    name: 'ANC 1-3 Dropout Rate',
                    description:
                        'Indicates the percentage of clients dropping out between the 1st and the 3rd ANC visit. Calculated as the difference between ANC1 and ANC3 by the ANC 1 visits.',
                    dimensionItemType: 'INDICATOR',
                    valueType: 'NUMBER',
                    totalAggregationType: 'AVERAGE',
                    indicatorType: {
                        name: 'Per cent',
                        displayName: 'Per cent',
                        factor: 100,
                        number: false,
                    },
                },
                lc3eMKXaEfw: {
                    uid: 'lc3eMKXaEfw',
                    code: 'OU_197385',
                    name: 'Bonthe',
                    dimensionItemType: 'ORGANISATION_UNIT',
                    valueType: 'TEXT',
                    totalAggregationType: 'SUM',
                },
                qhqAxPSTUXp: {
                    uid: 'qhqAxPSTUXp',
                    code: 'OU_226213',
                    name: 'Koinadugu',
                    dimensionItemType: 'ORGANISATION_UNIT',
                    valueType: 'TEXT',
                    totalAggregationType: 'SUM',
                },
                jmIPBj66vD6: {
                    uid: 'jmIPBj66vD6',
                    code: 'OU_246990',
                    name: 'Moyamba',
                    dimensionItemType: 'ORGANISATION_UNIT',
                    valueType: 'TEXT',
                    totalAggregationType: 'SUM',
                },
            },
            dimensions: {
                dx: ['ReUHfIn0pTQ', 'Uvn6LCg7dVU'],
                pe: [
                    '202404',
                    '202405',
                    '202406',
                    '202407',
                    '202408',
                    '202409',
                    '202410',
                    '202411',
                    '202412',
                    '202501',
                    '202502',
                    '202503',
                ],
                ou: [
                    'O6uvpzGd5pu',
                    'fdc6uOvgoji',
                    'lc3eMKXaEfw',
                    'jUb8gELQApl',
                    'PMa2VCrupOd',
                    'kJq2mPyFEHo',
                    'qhqAxPSTUXp',
                    'Vth0fbpFcsO',
                    'jmIPBj66vD6',
                    'TEQlaapDQoK',
                    'bL4ooGhyHRQ',
                    'eIQbndfxQMb',
                    'at6UHUQatSo',
                ],
                co: [],
            },
        },
    },
]

export const visualization = {
    name: 'ANC: Dropout rate v Coverage per district',
    created: '2021-03-29T07:40:30.569',
    lastUpdated: '2021-07-06T12:49:37.395',
    translations: [],
    favorites: [],
    lastUpdatedBy: {
        id: 'xE7jOejl9FI',
        code: null,
        name: 'John Traore',
        displayName: 'John Traore',
        username: 'admin',
    },
    regressionType: 'NONE',
    displayDensity: 'NORMAL',
    fontSize: 'NORMAL',
    sortOrder: 0,
    topLimit: 0,
    hideEmptyRows: false,
    showHierarchy: false,
    completedOnly: false,
    skipRounding: false,
    dataDimensionItems: [
        {
            indicator: {
                name: 'ANC 1-3 Dropout Rate',
                dimensionItemType: 'INDICATOR',
                displayName: 'ANC 1-3 Dropout Rate',
                access: {
                    manage: true,
                    externalize: true,
                    write: true,
                    read: true,
                    update: true,
                    delete: true,
                },
                displayShortName: 'ANC 1-3 Dropout Rate',
                id: 'ReUHfIn0pTQ',
            },
        },
        {
            indicator: {
                name: 'ANC 1 Coverage',
                dimensionItemType: 'INDICATOR',
                displayName: 'ANC 1 Coverage',
                access: {
                    manage: true,
                    externalize: true,
                    write: true,
                    read: true,
                    update: true,
                    delete: true,
                },
                displayShortName: 'ANC 1 Coverage',
                id: 'Uvn6LCg7dVU',
            },
        },
    ],
    subscribers: [],
    aggregationType: 'DEFAULT',
    digitGroupSeparator: 'SPACE',
    hideEmptyRowItems: 'NONE',
    noSpaceBetweenColumns: false,
    cumulativeValues: false,
    percentStackedValues: false,
    showData: true,
    colTotals: false,
    rowTotals: false,
    rowSubTotals: false,
    colSubTotals: false,
    hideTitle: false,
    hideSubtitle: false,
    showDimensionLabels: false,
    interpretations: [],
    type: 'SCATTER',
    reportingParams: {
        grandParentOrganisationUnit: false,
        parentOrganisationUnit: false,
        organisationUnit: false,
        reportingPeriod: false,
    },
    numberType: 'VALUE',
    fontStyle: {},
    colorSet: 'DEFAULT',
    yearlySeries: [],
    regression: false,
    hideEmptyColumns: false,
    fixColumnHeaders: false,
    fixRowHeaders: false,
    filters: [
        {
            items: [
                {
                    name: 'LAST_12_MONTHS',
                    dimensionItemType: 'PERIOD',
                    displayShortName: 'LAST_12_MONTHS',
                    displayName: 'LAST_12_MONTHS',
                    access: {
                        manage: true,
                        externalize: true,
                        write: true,
                        read: true,
                        update: true,
                        delete: true,
                    },
                    id: 'LAST_12_MONTHS',
                },
            ],
            dimension: 'pe',
        },
    ],
    parentGraphMap: {
        ImspTQPwCqd: '',
    },
    columns: [
        {
            items: [
                {
                    name: 'ANC 1-3 Dropout Rate',
                    dimensionItemType: 'INDICATOR',
                    displayName: 'ANC 1-3 Dropout Rate',
                    access: {
                        manage: true,
                        externalize: true,
                        write: true,
                        read: true,
                        update: true,
                        delete: true,
                    },
                    displayShortName: 'ANC 1-3 Dropout Rate',
                    id: 'ReUHfIn0pTQ',
                },
                {
                    name: 'ANC 1 Coverage',
                    dimensionItemType: 'INDICATOR',
                    displayName: 'ANC 1 Coverage',
                    access: {
                        manage: true,
                        externalize: true,
                        write: true,
                        read: true,
                        update: true,
                        delete: true,
                    },
                    displayShortName: 'ANC 1 Coverage',
                    id: 'Uvn6LCg7dVU',
                },
            ],
            dimension: 'dx',
        },
    ],
    rows: [
        {
            items: [
                {
                    name: 'Sierra Leone',
                    dimensionItemType: 'ORGANISATION_UNIT',
                    displayName: 'Sierra Leone',
                    access: {
                        manage: true,
                        externalize: true,
                        write: true,
                        read: true,
                        update: true,
                        delete: true,
                    },
                    displayShortName: 'Sierra Leone',
                    id: 'ImspTQPwCqd',
                },
                {
                    name: 'LEVEL-2',
                    displayName: 'LEVEL-2',
                    access: {
                        manage: true,
                        externalize: true,
                        write: true,
                        read: true,
                        update: true,
                        delete: true,
                    },
                    id: 'LEVEL-wjP19dkFeIk',
                },
            ],
            dimension: 'ou',
        },
    ],
    subscribed: false,
    displayName: 'ANC: Dropout rate v Coverage per district',
    access: {
        manage: true,
        externalize: true,
        write: true,
        read: true,
        update: true,
        delete: true,
    },
    favorite: false,
    user: {
        id: 'xE7jOejl9FI',
        code: null,
        name: 'John Traore',
        displayName: 'John Traore',
        username: 'admin',
    },
    href: 'http://localhost:8080/api/41/visualizations/w992mEjBzCB',
    id: 'w992mEjBzCB',
    legend: {
        showKey: false,
        style: 'FILL',
        strategy: 'FIXED',
    },
    sorting: [],
    series: [],
    icons: [],
    seriesKey: {
        hidden: false,
    },
    axes: [],
}

export const extraOptions = {
    animation: 0,
    dashboard: false,
    legendSets: [],
    onToggleContextualMenu: () => {
        console.log('on toggle contextual menu')
    },
}
