export const HIDE_EMPTY_ROW_ITEMS_BEFORE_FIRST = 'BEFORE_FIRST'
export const HIDE_EMPTY_ROW_ITEMS_AFTER_LAST = 'AFTER_LAST'
export const HIDE_EMPTY_ROW_ITEMS_BEFORE_FIRST_AFTER_LAST =
    'BEFORE_FIRST_AFTER_LAST'
export const HIDE_EMPTY_ROW_ITEMS_ALL = 'ALL'
