export const LAYOUT_TYPE_DEFAULT = 'LAYOUT_TYPE_DEFAULT'
export const LAYOUT_TYPE_PIE = 'LAYOUT_TYPE_PIE'
export const LAYOUT_TYPE_SINGLE_VALUE = 'LAYOUT_TYPE_SINGLE_VALUE'
export const LAYOUT_TYPE_YEAR_OVER_YEAR = 'LAYOUT_TYPE_YEAR_OVER_YEAR'
