export const baseDataObj = {
    response: {
        headers: [
            {
                name: 'dx',
                column: 'Data',
                valueType: 'TEXT',
                type: 'java.lang.String',
                hidden: false,
                meta: true,
            },
            {
                name: 'value',
                column: 'Value',
                valueType: 'NUMBER',
                type: 'java.lang.Double',
                hidden: false,
                meta: false,
            },
        ],
        metaData: {
            items: {
                2024: {
                    uid: '2024',
                    code: '2024',
                    name: '2024',
                    dimensionItemType: 'PERIOD',
                    valueType: 'TEXT',
                    totalAggregationType: 'SUM',
                    startDate: '2024-01-01T00:00:00.000',
                    endDate: '2024-12-31T00:00:00.000',
                },
                dx: {
                    uid: 'dx',
                    name: 'Data',
                    dimensionType: 'DATA_X',
                },
                pe: {
                    uid: 'pe',
                    name: 'Period',
                    dimensionType: 'PERIOD',
                },
                ou: {
                    uid: 'ou',
                    name: 'Organisation unit',
                    dimensionType: 'ORGANISATION_UNIT',
                },
                THIS_YEAR: {
                    name: 'This year',
                },
                abcWXyv0zpa: {
                    uid: 'abcWXyv0zpa',
                    name: 'Penta3 coverage under 1',
                    dimensionItemType: 'INDICATOR',
                    valueType: 'NUMBER',
                    totalAggregationType: 'AVERAGE',
                    indicatorType: {
                        name: 'Percentage',
                        displayName: 'Percentage',
                        factor: 100,
                        number: false,
                    },
                },
                E4h5WBOg71F: {
                    uid: 'E4h5WBOg71F',
                    code: 'GHA',
                    name: 'Ghana',
                    dimensionItemType: 'ORGANISATION_UNIT',
                    valueType: 'TEXT',
                    totalAggregationType: 'SUM',
                },
            },
            dimensions: {
                dx: ['abcWXyv0zpa'],
                pe: ['2024'],
                ou: ['E4h5WBOg71F'],
                co: [],
            },
        },
        rowContext: {},
        rows: [['abcWXyv0zpa', '79.41']],
        width: 2,
        height: 1,
        headerWidth: 2,
    },
    headers: [
        {
            name: 'dx',
            column: 'Data',
            valueType: 'TEXT',
            type: 'java.lang.String',
            hidden: false,
            meta: true,
            isPrefix: false,
            isCollect: false,
            index: 0,
        },
        {
            name: 'value',
            column: 'Value',
            valueType: 'NUMBER',
            type: 'java.lang.Double',
            hidden: false,
            meta: false,
            isPrefix: false,
            isCollect: false,
            index: 1,
        },
    ],
    rows: [['abcWXyv0zpa', '79.41']],
    metaData: {
        items: {
            2024: {
                uid: '2024',
                code: '2024',
                name: '2024',
                dimensionItemType: 'PERIOD',
                valueType: 'TEXT',
                totalAggregationType: 'SUM',
                startDate: '2024-01-01T00:00:00.000',
                endDate: '2024-12-31T00:00:00.000',
            },
            dx: {
                uid: 'dx',
                name: 'Data',
                dimensionType: 'DATA_X',
            },
            pe: {
                uid: 'pe',
                name: 'Period',
                dimensionType: 'PERIOD',
            },
            ou: {
                uid: 'ou',
                name: 'Organisation unit',
                dimensionType: 'ORGANISATION_UNIT',
            },
            THIS_YEAR: {
                name: 'This year',
            },
            abcWXyv0zpa: {
                uid: 'abcWXyv0zpa',
                name: 'Penta3 coverage under 1',
                dimensionItemType: 'INDICATOR',
                valueType: 'NUMBER',
                totalAggregationType: 'AVERAGE',
                indicatorType: {
                    name: 'Percentage',
                    displayName: 'Percentage',
                    factor: 100,
                    number: false,
                },
            },
            E4h5WBOg71F: {
                uid: 'E4h5WBOg71F',
                code: 'GHA',
                name: 'Ghana',
                dimensionItemType: 'ORGANISATION_UNIT',
                valueType: 'TEXT',
                totalAggregationType: 'SUM',
            },
        },
        dimensions: {
            dx: ['abcWXyv0zpa'],
            pe: ['2024'],
            ou: ['E4h5WBOg71F'],
            co: [],
        },
    },
}
export const layout = {
    name: 'RMNCA-N08: Immunisation Coverage (Penta3)',
    created: '2024-10-15T09:32:31.113',
    lastUpdated: '2024-11-11T23:49:50.939',
    translations: [],
    favorites: [],
    lastUpdatedBy: {
        id: 'ihTi0mMcuzs',
        code: null,
        name: 'Oswald Dachaga',
        displayName: 'Oswald Dachaga',
        username: 'Oswald',
    },
    regressionType: 'NONE',
    displayDensity: 'NORMAL',
    fontSize: 'NORMAL',
    sortOrder: 1,
    topLimit: 0,
    hideEmptyRows: false,
    showHierarchy: false,
    completedOnly: false,
    skipRounding: false,
    dataDimensionItems: [
        {
            indicator: {
                name: 'Penta3 coverage under 1',
                dimensionItemType: 'INDICATOR',
                displayName: 'Penta3 coverage under 1',
                access: {
                    manage: true,
                    externalize: true,
                    write: true,
                    read: true,
                    update: true,
                    delete: true,
                },
                displayShortName: 'Penta3 coverage under 1',
                id: 'abcWXyv0zpa',
            },
            dataDimensionItemType: 'INDICATOR',
        },
    ],
    subscribers: [],
    aggregationType: 'DEFAULT',
    digitGroupSeparator: 'SPACE',
    hideEmptyRowItems: 'NONE',
    noSpaceBetweenColumns: false,
    cumulativeValues: false,
    percentStackedValues: false,
    showData: true,
    colTotals: false,
    rowTotals: false,
    rowSubTotals: false,
    colSubTotals: false,
    hideTitle: false,
    hideSubtitle: false,
    showDimensionLabels: false,
    interpretations: [],
    type: 'SINGLE_VALUE',
    reportingParams: {
        grandParentOrganisationUnit: false,
        parentOrganisationUnit: false,
        organisationUnit: false,
        reportingPeriod: false,
    },
    numberType: 'VALUE',
    fontStyle: {
        visualizationTitle: {
            bold: true,
            textColor: '#104b9e',
        },
        visualizationSubtitle: {
            fontSize: 18,
        },
    },
    colorSet: 'GRAY',
    yearlySeries: [],
    regression: false,
    hideEmptyColumns: false,
    fixColumnHeaders: false,
    fixRowHeaders: false,
    rows: [],
    subscribed: false,
    parentGraphMap: {
        E4h5WBOg71F: '',
    },
    columns: [
        {
            items: [
                {
                    name: 'Penta3 coverage under 1',
                    dimensionItemType: 'INDICATOR',
                    displayName: 'Penta3 coverage under 1',
                    access: {
                        manage: true,
                        externalize: true,
                        write: true,
                        read: true,
                        update: true,
                        delete: true,
                    },
                    displayShortName: 'Penta3 coverage under 1',
                    id: 'abcWXyv0zpa',
                },
            ],
            dimension: 'dx',
        },
    ],
    filters: [
        {
            items: [
                {
                    name: 'THIS_YEAR',
                    dimensionItemType: 'PERIOD',
                    displayShortName: 'THIS_YEAR',
                    displayName: 'THIS_YEAR',
                    access: {
                        manage: true,
                        externalize: true,
                        write: true,
                        read: true,
                        update: true,
                        delete: true,
                    },
                    id: 'THIS_YEAR',
                },
            ],
            dimension: 'pe',
        },
        {
            items: [
                {
                    name: 'Ghana',
                    dimensionItemType: 'ORGANISATION_UNIT',
                    displayShortName: 'Ghana',
                    displayName: 'Ghana',
                    access: {
                        manage: true,
                        externalize: true,
                        write: true,
                        read: true,
                        update: true,
                        delete: true,
                    },
                    id: 'E4h5WBOg71F',
                },
            ],
            dimension: 'ou',
        },
    ],
    user: {
        id: 'ihTi0mMcuzs',
        code: null,
        name: 'Oswald Dachaga',
        displayName: 'Oswald Dachaga',
        username: 'Oswald',
    },
    displayName: 'RMNCA-N08: Immunisation Coverage (Penta3)',
    access: {
        manage: true,
        externalize: true,
        write: true,
        read: true,
        update: true,
        delete: true,
    },
    favorite: false,
    href: 'https://dhims.chimgh.org/dhims/api/41/visualizations/IziyerFnAdR',
    id: 'IziyerFnAdR',
    legend: {
        showKey: false,
        style: 'FILL',
        set: {
            name: 'Performance(+)',
            displayName: 'Performance(+)',
            id: 'j6zU70en9cL',
        },
        strategy: 'FIXED',
    },
    sorting: [],
    series: [
        {
            dimensionItem: 'THIS_YEAR',
            axis: 0,
        },
        {
            dimensionItem: 'LAST_YEAR',
            axis: 0,
        },
    ],
    icons: [],
    seriesKey: {
        hidden: false,
    },
    axes: [],
}

export const baseExtraOptions = {
    dashboard: false,
    animation: 200,
    legendSets: [
        {
            legends: [
                {
                    startValue: 80,
                    endValue: 100,
                    color: '#04341D',
                    id: 'btuo5dWE5ER',
                    name: '80 - 100',
                },
                {
                    startValue: 40,
                    endValue: 60,
                    color: '#F6F305',
                    id: 'AsDexAV4M1N',
                    name: '40 - 60',
                },
                {
                    startValue: 60,
                    endValue: 80,
                    color: '#06E84B',
                    id: 'BqHdGR4YNNq',
                    name: '60 - 80',
                },
                {
                    startValue: 20,
                    endValue: 40,
                    color: '#F67E04',
                    id: 'vVOTL88A673',
                    name: '20 - 40',
                },
                {
                    startValue: 0,
                    endValue: 20,
                    color: '#F80409',
                    id: 'Wt3Qw5tto0h',
                    name: '0 - 20',
                },
            ],
            id: 'j6zU70en9cL',
            name: 'Performance(+)',
        },
    ],
}
