export const SORT_ORDER_ASCENDING = 1
export const SORT_ORDER_DESCENDING = -1

export const CELL_TYPE_VALUE = 'value'
export const CELL_TYPE_SUBTOTAL = 'subtotal'
export const CELL_TYPE_TOTAL = 'total'

export const AGGREGATE_TYPE_SUM = 'SUM'
export const AGGREGATE_TYPE_AVERAGE = 'AVERAGE'
export const AGGREGATE_TYPE_NA = 'N/A'

export const NUMBER_TYPE_VALUE = 'VALUE'
export const NUMBER_TYPE_ROW_PERCENTAGE = 'ROW_PERCENTAGE'
export const NUMBER_TYPE_COLUMN_PERCENTAGE = 'COLUMN_PERCENTAGE'

export const BORDER_COLOR = '#b2b2b2'

export const FONT_SIZE_OPTION_SMALL = 'SMALL'
export const FONT_SIZE_SMALL = 10
export const FONT_SIZE_OPTION_NORMAL = 'NORMAL'
export const FONT_SIZE_NORMAL = 11
export const FONT_SIZE_OPTION_LARGE = 'LARGE'
export const FONT_SIZE_LARGE = 13

export const DISPLAY_DENSITY_OPTION_COMPACT = 'COMPACT'
export const DISPLAY_DENSITY_PADDING_COMPACT = 4
export const DISPLAY_DENSITY_OPTION_NORMAL = 'NORMAL'
export const DISPLAY_DENSITY_PADDING_NORMAL = 5
export const DISPLAY_DENSITY_OPTION_COMFORTABLE = 'COMFORTABLE'
export const DISPLAY_DENSITY_PADDING_COMFORTABLE = 7

export const CLIPPED_CELL_MAX_SIZE = 360
export const CLIPPED_CELL_MIN_SIZE = 36
export const WRAPPED_TEXT_JUSTIFY_BUFFER = 25
export const WRAPPED_TEXT_LINE_HEIGHT = 1.0

export const CLIPPED_AXIS_PARTITION_SIZE_PX = 1000
