name: 'dhis2: verify (lib)'

# Requirements:
#
# - Org secrets:
#       DHIS2_BOT_GITHUB_TOKEN
#       DHIS2_BOT_NPM_TOKEN

on: push

concurrency:
    group: ${{ github.workflow}}-${{ github.ref }}

env:
    GIT_AUTHOR_NAME: '@dhis2-bot'
    GIT_AUTHOR_EMAIL: 'apps@dhis2.org'
    GIT_COMMITTER_NAME: '@dhis2-bot'
    GIT_COMMITTER_EMAIL: 'apps@dhis2.org'
    D2_VERBOSE: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - uses: c-hive/gha-yarn-cache@v1
            - run: yarn install --frozen-lockfile

            - name: Build
              run: yarn d2-app-scripts build

            - uses: actions/upload-artifact@v2
              with:
                  name: lib-build
                  path: |
                      **/build
                      !**/node_modules
                  retention-days: 1

    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - uses: c-hive/gha-yarn-cache@v1
            - run: yarn install --frozen-lockfile

            - name: Lint
              run: yarn d2-style check

    commitlint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - uses: c-hive/gha-yarn-cache@v1
            - run: yarn install --frozen-lockfile
            - id: commitlint
              run: echo ::set-output name=config_path::$(node -e "process.stdout.write(require('@dhis2/cli-style').config.commitlint)")
            - uses: wagoid/commitlint-github-action@v4
              with:
                  configFile: ${{ steps.commitlint.outputs.config_path }}

    test:
        runs-on: ubuntu-latest
        needs: [build]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - uses: c-hive/gha-yarn-cache@v1
            - run: yarn install --frozen-lockfile

            - name: Test
              run: yarn d2-app-scripts test

    #e2e:
    #    runs-on: ubuntu-latest
    #    if: "!github.event.push.repository.fork && github.actor != 'dependabot[bot]'"
    #    needs: [build]
    #
    #    strategy:
    #        fail-fast: false
    #        matrix:
    #            containers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    #
    #    steps:
    #        - name: Checkout
    #          uses: actions/checkout@v2
    #
    #        - uses: actions/setup-node@v1
    #          with:
    #              node-version: 12.x
    #
    #        - uses: actions/download-artifact@v2
    #          with:
    #              name: lib-build
    #
    #        - name: End-to-End tests
    #          uses: cypress-io/github-action@v2
    #          with:
    #              # This should be a command that starts the server to test against.
    #              start: yarn start
    #              wait-on: 'http://localhost:3000'
    #              wait-on-timeout: 300
    #              record: true
    #              parallel: true
    #          env:
    #              BROWSER: none
    #              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #              CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
    #              CYPRESS_dhis2BaseUrl: https://debug.dhis2.org/dev
    #              CYPRESS_dhis2ApiVersion: 37
    #              CYPRESS_networkMode: stub

    publish:
        runs-on: ubuntu-latest
        needs: [build, lint, test] # add e2e if in use
        if: "!github.event.push.repository.fork && github.actor != 'dependabot[bot]'"
        steps:
            - uses: actions/checkout@v2
              with:
                  token: ${{secrets.DHIS2_BOT_GITHUB_TOKEN}}
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - uses: actions/download-artifact@v2
              with:
                  name: lib-build

            # ensure that d2-app-scripts is available
            - uses: c-hive/gha-yarn-cache@v1
            - run: yarn install --frozen-lockfile

            - uses: dhis2/action-semantic-release@master
              with:
                  publish-npm: true
                  publish-github: true
                  github-token: ${{secrets.DHIS2_BOT_GITHUB_TOKEN}}
                  npm-token: ${{secrets.DHIS2_BOT_NPM_TOKEN}}
