name: 'dhis2: test (node)'

on: push

jobs:
    unit:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20.x

            - name: Install
              run: yarn install --frozen-lockfile

            - name: Lint
              run: |
                  yarn d2-app-scripts i18n generate
                  yarn d2-style check

            - name: Test
              run: yarn test
        env:
            CI: true
